let ErrorType = {
    
    GENERAL_ERROR : {id: 1, httpCode: 600, message : "A big fuck up which we'll never tell you of had just happend. And now : A big fat lie....'A general error ....'", isShowStackTrace: true},
    USER_NAME_ALREADY_EXIST : {id: 2, httpCode: 601, message : "User name already exist", isShowStackTrace: false},
    BADREQUEST1:{id:3,httpCode:400,message:"you forgot enter your userName",isShowStackTrace:false},
    BADREQUEST2:{id:4,httpCode:400,message:"you forgot enter your password",isShowStackTrace:false},
    BADREQUEST3:{id:5,httpCode:400,message:"you forgot enter your firstName",isShowStackTrace:false},
    BADREQUEST4:{id:6,httpCode:400,message:"you forgot enter your lastName",isShowStackTrace:false},
    BADREQUEST5:{id:7,httpCode:400,message:"you forgot enter your type",isShowStackTrace:false},
    BADREQUEST6:{id:8,httpCode:400,message:"userName must be your email",isShowStackTrace:false},
    BADREQUEST7:{id:9,httpCode:400,message:"your password is too short",isShowStackTrace:false},
    BADREQUEST8:{id:10,httpCode:400,message:"your password is too long",isShowStackTrace:false},
    BADREQUEST9:{id:11,httpCode:400,message:"you forgot insert description",isShowStackTrace:false},
    BADREQUEST10:{id:12,httpCode:400,message:"you forgot insert destination",isShowStackTrace:false},
    BADREQUEST11:{id:13,httpCode:400,message:"you forgot insert picture",isShowStackTrace:false},
    BADREQUEST12:{id:14,httpCode:400,message:"you forgot insert travel date",isShowStackTrace:false},    
    BADREQUEST13:{id:15,httpCode:400,message:"you forgot insert return date",isShowStackTrace:false},
    BADREQUEST14:{id:16,httpCode:400,message:"you forgot insert the price",isShowStackTrace:false},
    BADREQUEST15:{id:17,httpCode:400,message:"you dont allow to do follow",isShowStackTrace:false},
    BADREQUEST16:{id:18,httpCode:400,message:"you dont allow to do unfollow",isShowStackTrace:false},
    BADREQUEST17:{id:23,httpCode:400,message:"you dont admin you cant add vacation",isShowStackTrace:false},
    BADREQUEST18:{id:24,httpCode:400,message:"you dont admin you cant delete vacation",isShowStackTrace:false},
    BADREQUEST19:{id:25,httpCode:400,message:"you dont admin you cant edit vacation",isShowStackTrace:false},
    BADREQUEST20:{id:26,httpCode:400,message:"you insert a bed travel date",isShowStackTrace:false},
    BADREQUEST21:{id:27,httpCode:400,message:"you insert a bed return date",isShowStackTrace:false},
    BADREQUEST22:{id:28,httpCode:400,message:"your picture must come from your brwoser",isShowStackTrace:false},
    BADREQUEST23:{id:29,httpCode:400,message:"you cant update that vacation you not admin",isShowStackTrace:false},
    BADREQUEST23:{id:29,httpCode:400,message:"the travel date can't came before the return date",isShowStackTrace:false},
    BADREQUEST24:{id:29,httpCode:400,message:"the travel date cant come before the return date",isShowStackTrace:false},
    UNAUTHORIZED1 : {id: 19, httpCode: 401, message : "Login failed, invalid user name or password", isShowStackTrace: false},
    UNAUTHORIZED2 : {id: 20, httpCode: 401, message : "your userName must be of kind email", isShowStackTrace: false},
    UNAUTHORIZED3 : {id: 21, httpCode: 401, message : "user not exit", isShowStackTrace: false},
    UNAUTHORIZED4 : {id: 22, httpCode: 401, message : "password is not correct", isShowStackTrace: false},
}

module.exports = ErrorType;